- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
    update_cache: yes

- name: Copy nginx site config
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/app

- name: Enable site
  ansible.builtin.file:
    src: /etc/nginx/sites-available/app
    dest: /etc/nginx/sites-enabled/app
    state: link

- name: Test nginx config
  ansible.builtin.command: nginx -t

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
    